/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCommissioningRouteImport } from './routes/_authenticated/commissioning'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDrawingsRouteImport } from './routes/_authenticated/drawings'
import { Route as AuthenticatedEquipmentRouteImport } from './routes/_authenticated/equipment'
import { Route as AuthenticatedInspectionRouteImport } from './routes/_authenticated/inspection'
import { Route as AuthenticatedMaterialsRouteImport } from './routes/_authenticated/materials'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedTestingRouteImport } from './routes/_authenticated/testing'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommissioningRoute =
  AuthenticatedCommissioningRouteImport.update({
    id: '/commissioning',
    path: '/commissioning',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDrawingsRoute = AuthenticatedDrawingsRouteImport.update({
  id: '/drawings',
  path: '/drawings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipmentRoute = AuthenticatedEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInspectionRoute = AuthenticatedInspectionRouteImport.update({
  id: '/inspection',
  path: '/inspection',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaterialsRoute = AuthenticatedMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTestingRoute = AuthenticatedTestingRouteImport.update({
  id: '/testing',
  path: '/testing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/commissioning': typeof AuthenticatedCommissioningRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/drawings': typeof AuthenticatedDrawingsRoute
  '/equipment': typeof AuthenticatedEquipmentRoute
  '/inspection': typeof AuthenticatedInspectionRoute
  '/materials': typeof AuthenticatedMaterialsRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/testing': typeof AuthenticatedTestingRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/commissioning': typeof AuthenticatedCommissioningRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/drawings': typeof AuthenticatedDrawingsRoute
  '/equipment': typeof AuthenticatedEquipmentRoute
  '/inspection': typeof AuthenticatedInspectionRoute
  '/materials': typeof AuthenticatedMaterialsRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/testing': typeof AuthenticatedTestingRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/commissioning': typeof AuthenticatedCommissioningRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/drawings': typeof AuthenticatedDrawingsRoute
  '/_authenticated/equipment': typeof AuthenticatedEquipmentRoute
  '/_authenticated/inspection': typeof AuthenticatedInspectionRoute
  '/_authenticated/materials': typeof AuthenticatedMaterialsRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/testing': typeof AuthenticatedTestingRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/commissioning'
    | '/documents'
    | '/drawings'
    | '/equipment'
    | '/inspection'
    | '/materials'
    | '/projects'
    | '/reports'
    | '/testing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/commissioning'
    | '/documents'
    | '/drawings'
    | '/equipment'
    | '/inspection'
    | '/materials'
    | '/projects'
    | '/reports'
    | '/testing'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/commissioning'
    | '/_authenticated/documents'
    | '/_authenticated/drawings'
    | '/_authenticated/equipment'
    | '/_authenticated/inspection'
    | '/_authenticated/materials'
    | '/_authenticated/projects'
    | '/_authenticated/reports'
    | '/_authenticated/testing'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commissioning': {
      id: '/_authenticated/commissioning'
      path: '/commissioning'
      fullPath: '/commissioning'
      preLoaderRoute: typeof AuthenticatedCommissioningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drawings': {
      id: '/_authenticated/drawings'
      path: '/drawings'
      fullPath: '/drawings'
      preLoaderRoute: typeof AuthenticatedDrawingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipment': {
      id: '/_authenticated/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof AuthenticatedEquipmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspection': {
      id: '/_authenticated/inspection'
      path: '/inspection'
      fullPath: '/inspection'
      preLoaderRoute: typeof AuthenticatedInspectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/materials': {
      id: '/_authenticated/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof AuthenticatedMaterialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/testing': {
      id: '/_authenticated/testing'
      path: '/testing'
      fullPath: '/testing'
      preLoaderRoute: typeof AuthenticatedTestingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCommissioningRoute: typeof AuthenticatedCommissioningRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedDrawingsRoute: typeof AuthenticatedDrawingsRoute
  AuthenticatedEquipmentRoute: typeof AuthenticatedEquipmentRoute
  AuthenticatedInspectionRoute: typeof AuthenticatedInspectionRoute
  AuthenticatedMaterialsRoute: typeof AuthenticatedMaterialsRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedTestingRoute: typeof AuthenticatedTestingRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCommissioningRoute: AuthenticatedCommissioningRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedDrawingsRoute: AuthenticatedDrawingsRoute,
  AuthenticatedEquipmentRoute: AuthenticatedEquipmentRoute,
  AuthenticatedInspectionRoute: AuthenticatedInspectionRoute,
  AuthenticatedMaterialsRoute: AuthenticatedMaterialsRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedTestingRoute: AuthenticatedTestingRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
