/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommissioningRouteImport } from './routes/commissioning'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DrawingsRouteImport } from './routes/drawings'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as InspectionRouteImport } from './routes/inspection'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as TestingRouteImport } from './routes/testing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissioningRoute = CommissioningRouteImport.update({
  id: '/commissioning',
  path: '/commissioning',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawingsRoute = DrawingsRouteImport.update({
  id: '/drawings',
  path: '/drawings',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionRoute = InspectionRouteImport.update({
  id: '/inspection',
  path: '/inspection',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const TestingRoute = TestingRouteImport.update({
  id: '/testing',
  path: '/testing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/commissioning': typeof CommissioningRoute
  '/documents': typeof DocumentsRoute
  '/drawings': typeof DrawingsRoute
  '/equipment': typeof EquipmentRoute
  '/inspection': typeof InspectionRoute
  '/materials': typeof MaterialsRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/testing': typeof TestingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/commissioning': typeof CommissioningRoute
  '/documents': typeof DocumentsRoute
  '/drawings': typeof DrawingsRoute
  '/equipment': typeof EquipmentRoute
  '/inspection': typeof InspectionRoute
  '/materials': typeof MaterialsRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/testing': typeof TestingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/commissioning': typeof CommissioningRoute
  '/documents': typeof DocumentsRoute
  '/drawings': typeof DrawingsRoute
  '/equipment': typeof EquipmentRoute
  '/inspection': typeof InspectionRoute
  '/materials': typeof MaterialsRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/testing': typeof TestingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/commissioning'
    | '/documents'
    | '/drawings'
    | '/equipment'
    | '/inspection'
    | '/materials'
    | '/projects'
    | '/reports'
    | '/testing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/commissioning'
    | '/documents'
    | '/drawings'
    | '/equipment'
    | '/inspection'
    | '/materials'
    | '/projects'
    | '/reports'
    | '/testing'
  id:
    | '__root__'
    | '/'
    | '/commissioning'
    | '/documents'
    | '/drawings'
    | '/equipment'
    | '/inspection'
    | '/materials'
    | '/projects'
    | '/reports'
    | '/testing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommissioningRoute: typeof CommissioningRoute
  DocumentsRoute: typeof DocumentsRoute
  DrawingsRoute: typeof DrawingsRoute
  EquipmentRoute: typeof EquipmentRoute
  InspectionRoute: typeof InspectionRoute
  MaterialsRoute: typeof MaterialsRoute
  ProjectsRoute: typeof ProjectsRoute
  ReportsRoute: typeof ReportsRoute
  TestingRoute: typeof TestingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commissioning': {
      id: '/commissioning'
      path: '/commissioning'
      fullPath: '/commissioning'
      preLoaderRoute: typeof CommissioningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawings': {
      id: '/drawings'
      path: '/drawings'
      fullPath: '/drawings'
      preLoaderRoute: typeof DrawingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspection': {
      id: '/inspection'
      path: '/inspection'
      fullPath: '/inspection'
      preLoaderRoute: typeof InspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testing': {
      id: '/testing'
      path: '/testing'
      fullPath: '/testing'
      preLoaderRoute: typeof TestingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommissioningRoute: CommissioningRoute,
  DocumentsRoute: DocumentsRoute,
  DrawingsRoute: DrawingsRoute,
  EquipmentRoute: EquipmentRoute,
  InspectionRoute: InspectionRoute,
  MaterialsRoute: MaterialsRoute,
  ProjectsRoute: ProjectsRoute,
  ReportsRoute: ReportsRoute,
  TestingRoute: TestingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
